server:
  port: '9000'
nacos:
  discovery:
    ip: 192.168.23.178
    port: 8848
  config:
    ip: 192.168.23.178
    port: 8848
  log: 'C:\GoWork\binbin\ggateway\data\nacos\log'
  cache: 'C:\GoWork\binbin\ggateway\data\nacos\cache'


pprof:
  server: localhost:6060